spring.application.name=training-platform
server.port=8081

## Demo default: H2 file database, so data persists across restarts.
#spring.datasource.url=jdbc:h2:file:./data/training-platform
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


 spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TrainingPlatformDb;encrypt=true;trustServerCertificate=true
 spring.datasource.username=sa
 spring.datasource.password=Welcome@123
 spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
